### ISSUE TITLE
QuickLook plugin not found

### ISSUE THREAD

**Issue by Evertt** [yllan/JXLook#10]
![image](https://user-images.githubusercontent.com/1267282/105740918-f7cb4300-5f39-11eb-9b1b-15f072fa891e.png)

**Comment by yllan** [comment]
Should be fixed at 24b4cd694fc1e634e75e1d5c700dda8842aa5c81

**Comment by Evertt** [comment]
Now that this is fixed, I indeed notice that having a working QuickLook Plugin doesn't mean that suddenly Preview can open the file too. Which is a shame to be honest. It would really be nice to be able to make plugins for Preview for decoding and encoding new image codecs.
