### ISSUE TITLE
Can not build submodule jpeg-xl on project directories different to author's

### ISSUE THREAD

**Issue by JLHwung** [yllan/JXLook#13]
The `jpeg-xl` submodule has hardcoded SRCROOT in `xcode/JPEGXL.xcodeproj/project.pbxproj`, considere replace `/Users/yllan/Projects/JXLook/jpeg-xl/` by `\"$SRCROOT\"` so it can be built on machines with a different directories.

However I can't build `jpeg-xl` even if I have replaced the SRCROOT:

```
make: *** /path/to/jpeg-xl/xcode/third_party/highway: No such file or directory.  Stop.
```

**Comment by yllan** [comment]
I give up the CMake generated xcodeproj, which is too buggy and has lots of hardcoded incorrect value.
Now, I just build the static library and copy the result. I've add a [script](https://github.com/yllan/JXLook/blob/main/build_libjxl.sh) to do this.
