### ISSUE TITLE
Doesn't work for black-and-white .jxl images

### ISSUE THREAD

**Issue by cessez-le-feu** [yllan/JXLook#14]
Hello,

I'm using the official binary that you provide in "JXLook-0.1.3.app.tbz", and it works for many .jxl images, but it doesn't for black-and-white ones.

I'm attaching to this ticket both an original .jpg file, and the .jxl image converted from the original. And JXLook is unable to show the converted image.

Here are screenshots proving this:

![screenshot1](https://user-images.githubusercontent.com/87081549/124780435-96f45d80-df10-11eb-8069-974a122637e8.png)
![screenshot2](https://user-images.githubusercontent.com/87081549/124780457-9cea3e80-df10-11eb-89b4-d63e5d0cd68a.png)

Attachments:
[x1A27_L8xbE.jpg.zip](https://github.com/yllan/JXLook/files/6778105/x1A27_L8xbE.jpg.zip)
[x1A27_L8xbE.jxl.zip](https://github.com/yllan/JXLook/files/6778107/x1A27_L8xbE.jxl.zip)

**Comment by yllan** [comment]
Thanks for reporting. Please check the latest version [0.1.4](https://github.com/yllan/JXLook/releases/download/v0.1.4/JXLook-0.1.4.app.tbz). It should support greyscale image.

**Comment by cessez-le-feu** [comment]
Yes, the problem is now solved in 0.1.4. Thank you for your reactivity and for providing the app for free! Bye-bye
