### ISSUE TITLE
Thumbnail plugin

### ISSUE THREAD

**Issue by yllan** [yllan/JXLook#5]

**Comment by Evertt** [comment]
Isn't this the same as the QuickLook plugin? Again, since I've installed `WebpQuickLook.qlgenerator` I now see WebP thumbnails in Finder too.

**Comment by yllan** [comment]
@Evertt Are you using Big Sur? It seems that macOS Big Sur already support WebP system-wide. That is, I don't have the `WebpQuickLook.qlgenerator` installed and I can still open `*.webp` in Preview.app or preview in Finder.

Let me explain this:
There are two kinds of QuickLook plugin. 
- One is the good old `*.qlgenerator`, which existed since some early version of macOS, resides in `~/Library/QuickLook`, `/Library/QuickLook` or `/System/Library/QuickLook`. You can see even Apple provides their service in this way.
- Since macOS 10.15, Apple encourage developers use the new `QuickLook.appex`, which is a bundle embedded inside an app. I believe this model was came from iOS land. 

I'm using the second approach, because:
1. Checking the [Apple's developer document](https://developer.apple.com/documentation/quicklook), nearly every function in [Previews or Thumbnail Images for macOS 10.14 or Earlier](https://developer.apple.com/documentation/quicklook/previews_or_thumbnail_images_for_macos_10_14_or_earlier) (good old `qlgenerator`) was marked deprecated.
2. You can't even find the good old `qlgenerator` project type in Xcode 12. 😢

Back to the topic. I believe the [Thumbnail Plugin](https://developer.apple.com/documentation/quicklookthumbnailing) was used to generate Finder icon instead of the preview image in the new QuickLook architecture.

**Comment by Evertt** [comment]
> Are you using Big Sur? It seems that macOS Big Sur already support WebP system-wide. That is, I don't have the WebpQuickLook.qlgenerator installed and I can still open *.webp in Preview.app or preview in Finder.

Huh, weird, I was convinced that I couldn't do that before I installed the plugin. But now I deleted the plugin and indeed I can still view WebP images.

Okay, in that case, don't mind me, I don't know what I'm talking about 😅

**Comment by yllan** [comment]
libjxl (0.3.0) didn't support progressive decoding yet. Waiting for it to support.
